version: '3.8'

services:
  coffiary_tg_bot:
    image: "bot"
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    command: python3 -m bot
    deploy:
      restart_policy:
        condition: any
    env_file:
      - ".env"
    ports:
      - "8085:80"  # Открываем порт 8081 для бота
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - mysql  # Указываем зависимость от MySQL

  coffiary_api:
    image: "api"
    build:
      context: ./infrastructure/api
    #working_dir: "/usr/src/app/infrastructure/api"
    working_dir: "/usr/src/app/api"
    volumes:
      - .:/usr/src/app/api
#    volumes:
#      - ./infrastructure:/usr/src/app/infrastructure
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "infrastructure.api.app:app"]
    #command: python3 app.py
    deploy:
      restart_policy:
        condition: any
    env_file:
      - ".env"
    ports:
      - "8084:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - mysql


  coffiary_mysql:
    image: "mysql:8.0"
    env_file:
      - ".env"
    ports:
      - "3306:3306"  # Открываем порт 3306 для MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Сохраняем данные MySQL на локальном хосте
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # Добавляем кастомную конфигурацию
    deploy:
      restart_policy:
        condition: any

volumes:
  mysql_data:
