"""описание миграции

Revision ID: 133ed29010e3
Revises: 343bb188ff78
Create Date: 2024-09-29 18:53:31.291489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133ed29010e3'
down_revision: Union[str, None] = '343bb188ff78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('photo_url', sa.String(length=400), nullable=True),
    sa.Column('water_volume', sa.Numeric(precision=4, scale=0), nullable=True),
    sa.Column('water_temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('amount_of_coffee', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('brew_time', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('grind_size', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('grade', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('coffee_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('month_block', sa.String(length=50), nullable=True),
    sa.Column('day_block', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('is_telegram_on', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('registred_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.drop_column('users', 'language')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'active')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('users', sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('language', mysql.VARCHAR(length=10), server_default=sa.text("'en'"), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'registred_date')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'is_telegram_on')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'id')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
